site_name: 'NGSI-v2 Smart Supermarket Tutorials'
site_url: 'https://fiware-tutorials.readthedocs.org'
repo_url: 'https://github.com/fiware/tutorials.NGSI-v2'
site_description: FIWARE NGSI-v2 Tutorial Documentation (Smart Supermarket)
docs_dir: docs
site_dir: html
use_directory_urls: false
theme: readthedocs
markdown_extensions:
  - fenced_code
extra_css:
  - 'https://www.fiware.org/style/fiware_readthedocs.css'
  - 'https://www.fiware.org/style/fiware_readthedocs_neutral.css'
  - 'https://fiware.github.io/catalogue/ngsi-v2.css'
nav:
  - Home: index.md
  - '<span style=''font-size:105%;padding:0px''>Core Context Management: </span><span style=''font-size:105%;padding:0px''>The NGSI-v2 Interface</span>':
      - Getting Started with NGSI-v2: getting-started.md
      - Entity Relationships: entity-relationships.md
      - CRUD Operations: crud-operations.md
      - Context Providers: context-providers.md
      - Accessing Context: accessing-context.md
      - Subscriptions: subscriptions.md
  - IoT Agents & Robots:
      - IoT Sensors: iot-sensors.md
      - IoT Agent (Ultralight): iot-agent.md
      - IoT Agent (JSON): iot-agent-json.md
      - IoT over MQTT: iot-over-mqtt.md
      - IoT over IOTA Tangle: iot-over-iota-tangle.md
      - Custom IoT Agent (XML): custom-iot-agent.md
      - Fast RTPS-Micro RTPS: fast-rtps-micro-rtps.md
  - '<span style=''font-size:105%;padding:0px''>Core Context Management: </span><span style=''font-size:105%;padding:0px''>Processing & History Management</span>':
      - Persisting Context (Apache Flume): historic-context-flume.md
      - Persisting Context (Apache NIFI): historic-context-nifi.md
      - Short Term History: short-term-history.md
      - Time-Series Data: time-series-data.md
      - Big Data Analysis (Flink): big-data-flink.md
      - Big Data Analysis (Spark): big-data-spark.md
  - Identity Management:
      - Administrating Users: identity-management.md
      - Managing Roles and Permissions: roles-permissions.md
      - Securing Application Access: securing-access.md
      - Securing Microservices: pep-proxy.md
      - Ruleset-based Permissons: xacml-access-rules.md
      - Administrating XACML Rules: administrating-xacml.md
      - Authenticating Identities (Open-ID): open-id-connect.md
  - 'Processing, Analysis and Visualization':
      - Application Mashups: application-mashups.md
      - Media Streams: media-streams.md
      - Cloud Edge Computing: edge-computing.md
  - NGSI-LD for NGSI-v2 Developers:
      - Linked Data: linked-data.md
      - Relationships & Data Models: relationships-linked-data.md
      - Traversing Linked Data: working-with-linked-data.md
      - Subscriptions and Registrations: ld-subscriptions-registrations.md
  - Appendix:
      - Curl Commands: cmds/administrating-xacml.md
      - Installing Docker: docker-ubuntu.md
      - Using Virtual Box: virtual-box.md
      - Using WSL: wsl.md
      - Troubleshooting: troubleshooting.md
