name: Deploy Baseimage

# Will only run on pushes to the docker directory, to prevent a rebuild of the base image on every change.
# We also only build on develop, so that the latest base image is always valid. If you want to verify with  an snapshot image, please push one
# to your local registry and build from there.

on:
  push:
    paths:
      - docker/**
      - context-provider/**
    branches:
      - master
  workflow_dispatch:

env:
  IMAGE_NAME: fiware/tutorials.context-provider:latest

jobs:
  deploy:
    runs-on: ubuntu-18.04
    if: ${{ github.repository_owner == 'FIWARE' }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - name: Docker meta (Distroless)
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ env.IMAGE_NAME }}
          labels: |
            org.opencontainers.image.title=FIWARE NGSI-v2 Tutorials
            org.opencontainers.image.description=Simple Supermarket Node.js express application for use with the FIWARE NGSI-v2 tutorials
      - name: Build and push (Distroless)
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}
            ghcr.io/${{ env.IMAGE_NAME }}
            quay.io/${{ env.IMAGE_NAME }}
          file: docker/Dockerfile
          labels: ${{ steps.meta.outputs.labels }}
